wandb_version: 1

architecture:
  desc: null
  value: PLIP
dataset:
  desc: null
  value: PanNuke
epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1702215336.773016
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.1
      6: 4.35.2
      8:
      - 2
      - 5
      13: linux-x86_64
